export const LOADER_COMPLETION = 'LOADER_COMPLETION'

export const CONNECT_SOCKET_REQUESTED = 'CONNECT_SOCKET_REQUESTED'
export const CONNECT_SOCKET_SUCCEEDED = 'CONNECT_SOCKET_SUCCEEDED'
export const CONNECT_SOCKET_FAILED    = 'CONNECT_SOCKET_FAILED'

export const QUERY_PLAYER = 'QUERY_PLAYER'
export const QUERY_REGION = 'QUERY_REGION'

export const UPDATE_PLAYER = 'UPDATE_PLAYER'
export const UPDATE_REGION = 'UPDATE_REGION'

export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET'