export const ASSET_LOADER_COMPLETION = 'ASSET_LOADER_COMPLETION'

export const CONNECT_SOCKET_REQUESTED = 'CONNECT_SOCKET_REQUESTED'
export const CONNECT_SOCKET_SUCCEEDED = 'CONNECT_SOCKET_SUCCEEDED'
export const CONNECT_SOCKET_FAILED    = 'CONNECT_SOCKET_FAILED'

export const QUERY_PLAYER_REQUESTED  = 'QUERY_PLAYER_REQUESTED'
export const QUERY_PLAYER_RECEIVED   = 'QUERY_PLAYER_RECEIVED'
export const QUERY_REGION_REQUESTED  = 'QUERY_REGION_REQUESTED'
export const QUERY_REGION_RECEIVED   = 'QUERY_REGION_RECEIVED'
export const QUERY_CYCLING_REQUESTED = 'QUERY_CYCLING_REQUESTED'
export const QUERY_CYCLING_RECEIVED  = 'QUERY_CYCLING_RECEIVED'
export const QUERY_UNKNOWN_RECEIVED  = 'QUERY_UNKNOWN_RECEIVED'

export const UPDATE_PLAYER = 'UPDATE_PLAYER'
export const UPDATE_REGION = 'UPDATE_REGION'

